package chat

import (
	"fmt"
	"time"

	"github.com/weatherjean/shell3/internal/llm"
)

// EventKind classifies stream events emitted by a chat session.
type EventKind int

const (
	// EventSessionStart fires once per session, before any turn. Meta
	// carries startup metadata (persona, model, headless flag, etc.).
	EventSessionStart EventKind = iota
	// EventSessionEnd fires once at session teardown. Meta["status"] is
	// "ok" or an error label.
	EventSessionEnd
	// EventUserMessage fires when the user submits input. Role and Text
	// are populated.
	EventUserMessage
	// EventAssistantToken fires for each streamed assistant token. Text
	// is the token delta; high-volume.
	EventAssistantToken
	// EventAssistantMessage fires once per assistant turn after streaming
	// completes. Role is "assistant" and Text is the full message.
	EventAssistantMessage
	// EventToolCall fires when the assistant invokes a tool. ToolName,
	// ToolInput, and ToolCallID are populated.
	EventToolCall
	// EventToolResult fires after a tool returns. ToolName, ToolOutput,
	// ToolCallID, and ToolError are populated.
	EventToolResult
	// EventError fires when a non-fatal error occurs (stream failure,
	// hook denial, etc.). Text holds the error message.
	EventError
	// EventUsage fires when the provider reports per-stream token usage.
	// Usage is populated.
	EventUsage
	// EventAssistantReasoning fires for reasoning/thinking tokens on
	// providers that surface them separately. Text holds the reasoning
	// delta or block.
	EventAssistantReasoning
	// EventTurnDone fires once when a full user→assistant turn (including
	// any tool roundtrips) completes. Usage carries cumulative totals.
	EventTurnDone
	// EventSystemReminder fires when the package injects a
	// <system-reminder> block (model change, context usage threshold).
	// Text contains the rendered reminder.
	EventSystemReminder
	// EventRetry fires when a transient request failure is about to be
	// retried. Text holds a human-readable summary (reason + attempt count).
	EventRetry
)

func (k EventKind) String() string {
	switch k {
	case EventSessionStart:
		return "session_start"
	case EventSessionEnd:
		return "session_end"
	case EventUserMessage:
		return "user_message"
	case EventAssistantToken:
		return "assistant_token"
	case EventAssistantMessage:
		return "assistant_message"
	case EventToolCall:
		return "tool_call"
	case EventToolResult:
		return "tool_result"
	case EventError:
		return "error"
	case EventUsage:
		return "usage"
	case EventAssistantReasoning:
		return "assistant_reasoning"
	case EventTurnDone:
		return "turn_done"
	case EventSystemReminder:
		return "system_reminder"
	case EventRetry:
		return "retry"
	}
	return "unknown"
}

// Event is a single observable occurrence during a chat session. Consumers
// (TUI, JSONL sink, embedders) receive each Event via the SessionOpts.Sink
// callback. Most fields are optional and only populated for certain Kinds; see
// the EventKind constants for which fields each kind sets.
type Event struct {
	// Kind discriminates the event; consumers switch on it.
	Kind EventKind
	// Time is when the event was emitted.
	Time time.Time
	// SessionID is the store session id (0 if no store is configured).
	SessionID int64

	// Text is the message payload for token, message, reasoning, error,
	// and system-reminder events.
	Text string
	// Err is the underlying typed error on EventError, so consumers can use
	// errors.Is/errors.As. Text holds its message for display. Not serialized
	// (the JSONL sink uses Text).
	Err error `json:"-"`
	// Role is "user" or "assistant" for message events.
	Role string
	// ToolName is set on tool_call and tool_result.
	ToolName string
	// ToolInput is the raw JSON args on tool_call.
	ToolInput string
	// ToolOutput is the tool's return string on tool_result.
	ToolOutput string
	// ToolError is true when the tool result represents an error.
	ToolError bool
	// ToolCallID is the sequential id linking a tool_call to its
	// tool_result.
	ToolCallID string
	// Usage carries token accounting on usage and turn_done events.
	Usage *EventUsageData
	// Meta carries small key/value extras (e.g. session_end status,
	// session_start metadata).
	Meta map[string]string
}

// EventUsageData captures token accounting reported by the provider. Set on
// EventUsage (per-stream) and EventTurnDone (cumulative across a turn's
// roundtrips).
type EventUsageData struct {
	// PromptTokens counts tokens sent to the model.
	PromptTokens int
	// CompletionTokens counts tokens generated by the model.
	CompletionTokens int
	// TotalTokens is PromptTokens + CompletionTokens, as reported.
	TotalTokens int
}

func emitSessionStart(s *Session, meta map[string]string) {
	emit(s, Event{
		Kind:      EventSessionStart,
		Time:      time.Now(),
		SessionID: s.id,
		Meta:      meta,
	})
}

func emitSessionEnd(s *Session, status string) {
	emit(s, Event{
		Kind:      EventSessionEnd,
		Time:      time.Now(),
		SessionID: s.id,
		Meta:      map[string]string{"status": status},
	})
}

func emitToolCall(s *Session, callID, name, input string) {
	emit(s, Event{
		Kind:       EventToolCall,
		Time:       time.Now(),
		SessionID:  s.id,
		ToolName:   name,
		ToolInput:  input,
		ToolCallID: callID,
	})
}

func emitToolResult(s *Session, callID, name, output string, isErr bool) {
	emit(s, Event{
		Kind:       EventToolResult,
		Time:       time.Now(),
		SessionID:  s.id,
		ToolName:   name,
		ToolOutput: output,
		ToolError:  isErr,
		ToolCallID: callID,
	})
}

func emitAssistantToken(s *Session, text string) {
	emit(s, Event{Kind: EventAssistantToken, Time: time.Now(), SessionID: s.id, Text: text})
}

func emitAssistantMessage(s *Session, text string) {
	emit(s, Event{Kind: EventAssistantMessage, Time: time.Now(), SessionID: s.id, Role: "assistant", Text: text})
}

func emitUserMessage(s *Session, text string) {
	emit(s, Event{Kind: EventUserMessage, Time: time.Now(), SessionID: s.id, Role: "user", Text: text})
}

// emitError emits the turn's terminal error event. err must be non-nil: Text
// carries its message for display, Err carries the value itself so embedders
// can errors.Is/errors.As it.
func emitError(s *Session, err error) {
	emit(s, Event{Kind: EventError, Time: time.Now(), SessionID: s.id, Text: err.Error(), Err: err})
}

func emitUsage(s *Session, prompt, completion, total int) {
	emit(s, Event{
		Kind:      EventUsage,
		Time:      time.Now(),
		SessionID: s.id,
		Usage:     &EventUsageData{PromptTokens: prompt, CompletionTokens: completion, TotalTokens: total},
	})
}

func emitAssistantReasoning(s *Session, text string) {
	emit(s, Event{Kind: EventAssistantReasoning, Time: time.Now(), SessionID: s.id, Text: text})
}

func emitSystemReminder(s *Session, text string) {
	emit(s, Event{Kind: EventSystemReminder, Time: time.Now(), SessionID: s.id, Text: text})
}

func emitRetry(s *Session, n *llm.RetryNotice) {
	text := fmt.Sprintf("stream failed (%s), retrying (%d/%d)", n.Reason, n.Attempt, n.Max)
	emit(s, Event{Kind: EventRetry, Time: time.Now(), SessionID: s.id, Text: text})
}

func emitTurnDone(s *Session, prompt, completion, total int) {
	emit(s, Event{
		Kind:      EventTurnDone,
		Time:      time.Now(),
		SessionID: s.id,
		Usage:     &EventUsageData{PromptTokens: prompt, CompletionTokens: completion, TotalTokens: total},
	})
}

// emit delivers an event to the session sink. Delivery is synchronous and
// inline on the turn goroutine, so events are never dropped and ordering is
// exactly the emit order.
func emit(s *Session, ev Event) {
	if s == nil || s.sink == nil {
		return
	}
	s.sink(ev)
}
